let localHostEnv = false;
let _host = localHostEnv ? 'http://crm.dev/mobile/Api/' : 'http://crmapi.24parking.com.cn/mobile/Api/';
let ApiRoute = {
  getarea: _host + 'getarea',
  getsporthall: _host + 'getsporthall',
  getcoachinfo: _host + 'getcoachinfo',
  getvalidatecode: _host + 'getvalidatecode',
  userreg: _host + 'userreg',
  userlogin: _host + 'userlogin',
  changepwd: _host + 'changepwd',
  setnewpwd: _host + 'setnewpwd',
  setusername: _host + 'setusername',
  getsporthalldetail: _host + 'getsporthalldetail',
  getcoachlist: _host + 'getcoachlist',
  confirmorder: _host + 'confirmorder',
  getmycourse: _host + 'getmycourse',
  accountrecharge: _host + 'accountrecharge',
  getrechargelist: _host + 'getrechargelist',
  getaccountchange: _host + 'getaccountchange',
  cancelcourse: _host + 'cancelcourse',
  getuserinfo: _host + 'getuserinfo',
  setuserschedule: _host + 'setuserschedule',
  uploadimage: _host + 'uploadimage',
  userevaluate: _host + 'userevaluate',
  getuserorder: _host + 'getuserorder',
  getusercourse: _host + 'getusercourse',
  getcoachchedule: _host + 'getcoachchedule',
  orderpay: _host + 'orderpay',
  createorder: _host + 'createorder',
  getcoachorder: _host + 'getcoachorder',
  getstudent: _host + 'getstudent',
  getschedulebycoach: _host + 'getschedulebycoach',
  getinfobycoach: _host + 'getinfobycoach',
  getstudentcourselog: _host + 'getstudentcourselog',
  getsignqrcode: _host + 'getsignqrcode',
  getoauthinfo: _host + 'getoauthinfo',
  searchstudent: _host + 'searchstudent',
  getcoachevaluate: _host + 'getcoachevaluate',
  getcoachcourselog: _host + 'getcoachcourselog',
  getcoachsale:_host+'getcoachsale',
}
export {ApiRoute}
